config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :ratings
  end

  resources :players do
    resources :notes
    resources :ratings
  end

  resources :events

  get 'events/:id/teams' => 'events#get_teams', as: :teams

  root 'welcome#login'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/event.rb
class Event < ActiveRecord::Base
	def number_of_teams
		if self.number_of_players == 16
			return 2
		else
			return (self.number_of_players / 6)
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def get_teams
		@event = Event.find([params[:id]]).first
		@players_to_create = Array.new
		@players_to_show = Array.new
		access_token = current_user.oauth_token
		Koala.config.api_version = "v2.5"
		@graph = Koala::Facebook::API.new(access_token)
		Rails.logger.debug(Time.now.to_i)
		connections = @graph.get_connections('848848561801054', 'events', since: Time.now.to_i)
		event_id = nil
		start_time = nil

		connections.each do | connection |
			Rails.logger.debug('ID! '+connection['id'])
			name = connection['name']
			start_time = connection['start_time']
			if (name.downcase.include? @event.day_of_week.downcase) && (start_time.include? (@event.time.to_s+':00:00'))
				event_id = connection['id']
				break
			end
		end

		if event_id.present?

			attending = @graph.get_connections(event_id, 'attending')

			attending.each do | attendee |

				player = Player.find_by name: attendee['name']

				if player.present?
					@players_to_show.push(player)
					changed = false

					if player['last_active'] != start_time
						player.last_active = start_time
						changed = true
					end

					if player['app_facebook_id'].nil?
						player.app_facebook_id = attendee['id']
						changed = true
					end

					if changed == true
						player.save!
					end
				else
					@players_to_create.push(attendee['name'])
				end

			end

			
		else

			Rails.logger.debug('Could not find event')
		end
	end
end

app/views/events/get_teams.html.erb
<div class="wrapper">
	<div class="player-list-wrapper">
		<% if @players_to_create.length > 0 %>
			<div class="alert alert-danger" role="alert">
			  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				Error!  Error! The following players have not been found in the database:
				<br/><br/>
				<% @players_to_create.each do | player_to_create | %>
					<div><%= player_to_create %></div>
				<% end %>
				<br/>
				Please create them and try again.
			<div>
		<% else %>
			<div>Day: <%= @event.day_of_week %></div>
			<div>Time: <%= @event.time.to_s %>:00</div>
			<div># Teams: <span id="num-teams"><%= @event.number_of_teams %></span></div>
			<table class="table player-going-table">
				<caption>Players going:</caption>
				<thead>
					<th>Name</th>
					<th>Rating</th>
					<th>Goalie</th>
				</thead>
				<tbody>
					<% @players_to_show.each do | player_to_show | %>
						<tr>
							<td><%= link_to player_to_show.name, player_path(player_to_show) %></td>
							<td><%= number_with_precision(player_to_show.avg_player_rating, :precision => 1) %></td>
							<td>
								<% if player_to_show.is_goalie %>
									&#10004;
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<!--<div class="pitch"></div>-->
		<% end %>
	</div>
	<% if @players_to_create.length == 0 %>
		<div class="teams-wrapper">
			<div class="alertContainer"></div>
			<div class="checkbox">
				<label for="ensure_goalies">
					<span>Ensure there is at least one goalie on each side</span>
				</label>
				<input type="checkbox" id="ensure_goalies" class="pull-right">
			</div>
			<div id="max-rating">
				<label>Maximum rating difference between any two teams</label>
				<input type="number" step="0.5" min="0" value="0.5">
			</div>
			<div class="generate-btn">
				<button onclick="generateTeams();">Generate my teams, bitch!</button>
			</div>
			<div id="teams">

			</div>
		</div>
	<% end %>
</div>

app/views/events/index.html.erb
<div>
<% @events.each do | event | %>

	<%= link_to teams_path(event), :class => "btn btn-primary btnCustom" do %>
		<div class="event-text"><%= event.day_of_week %> @ <%= event.time %>:00</div>
	<% end %>
<% end %>
</div>