config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :ratings
  end

  resources :players do
    resources :notes
    resources :ratings
  end

  resources :events

  get 'events/:id/teams' => 'events#get_teams', as: :teams

  root 'welcome#login'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :ratings
	has_many :notes
	has_many :histories

	validates :name, :presence => true
	validates :facebook_id, :presence => true

	def avg_player_rating
  	
  		self.ratings.average('rating')
  	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /players
  # GET /players.json
  def index
    @players = Player.all.order('Name ASC')

    unless current_user.nil?

      @player_image_urls = Hash.new
      @graph = Koala::Facebook::API.new(current_user.oauth_token)
      offset = 0;
      finished = false
      @pictures = Array.new

      while finished == false do
        
        temp_pictures = @graph.batch do | batch_api |
          players_batch = @players.limit(50).offset(offset)
          players_batch.each do | player |
            if player.facebook_id.present?
              batch_api.get_picture(player.facebook_id)
            end

            offset += 1
          end

          finished = players_batch.size != 50
        end

        @pictures.concat temp_pictures
      end  

      i = 0

      @players.each do | player |
        if player.facebook_id.present?
          @player_image_urls[player.id] = @pictures[i]
          i+=1
        end  
      end

      Rails.logger.debug(@player_image_urls)
    end

    respond_with(@players)
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @graph = Koala::Facebook::API.new(current_user.oauth_token)

    if @player.facebook_id.present?
        @profile_picture = @graph.get_picture(@player.facebook_id, { 'type' => 'large' })   
    end

    respond_with(@player)
  end

  # GET /players/new
  def new
    @player = Player.new
    respond_with(@player)
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to player_path(@player)
    else
      respond_with @player
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :is_goalie, :facebook_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :facebook_id %>&nbsp;<span>(Go to <a target="_blank" href="http://findmyfbid.com">findmyfbid.com</a> and enter the Facebook username to get the id)</span><br>
    <%= f.text_field :facebook_id %>
  </div>
  <div class="field">
    <%= f.label 'Goalie?' %><br>
    <%= f.check_box :is_goalie %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-info'%>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<div id="players-container">
  <p id="notice"><%= notice %></p>
  <div class="btn-container">
    <%= button_to 'New Player', new_player_path, :class => 'btn btn-info', :method => :get %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th style="width:75px;"></th>
        <th>Name</th>
        <th class="center">Last Active</th>
        <th class="center">Goalie?</th>
        <th class="center">Avg Rating</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><img src="<%= @player_image_urls[player.id] %>"></img></td>
          <td><%= link_to player.name, player %></td>
          <td class="center"><%= player.last_active %></td>
          <td class="center">
            <% if player.is_goalie %>
            &#10004;
            <% end %>
          </td>
          <td class="center"><%= number_with_precision(player.avg_player_rating, :precision => 1) %></td>
          <td><%= link_to 'View', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>  
</div>

app/views/players/new.html.erb
<div id="new-player-container">
	<h1>New Player</h1>

	<%= render 'form' %>

	<%= link_to 'Back', players_path %>
</div>

app/views/players/show.html.erb
<div id="player-container">
	<div class="picture-xl">
		<img src="<%= @profile_picture %>"></img>
	</div>
	<h1><%= @player.name %></h1>
	<p>
	  <strong>Last Active:</strong>
	  <%= @player.last_active %>
	</p>

	<p>
	  <strong>Is goalie:</strong>
	  <%= @player.is_goalie %>
	</p>

	<canvas id="rating-placeholder"></canvas>

	<% unless @player.histories.empty? %>
		<h4>Rating Changes</h3>
		<table class="table table-striped">
			<thead>
				<th>Admin</th>
				<th>Old Rating</th>
				<th>New Rating</th>
				<th>Date Changed</th>
			</thead>
			<tbody>
				<% @player.histories.each do | rating | %>
					<tr>
						<td><%= rating.user.name %></td>
						<td><%= rating.old_rating %></td>
						<td><%= rating.new_rating %></td>
						<td><%= rating.created_at.strftime("%A, %d %b %Y") %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>

	<%= link_to 'Edit', edit_player_path(@player) %> |
	<%= link_to 'Back', players_path %>

	<script>
		var ratings = new Array();
		<% @player.ratings.each do | rating | %>
		var rating = new Object();
		rating.rating = '<%= rating.rating %>';
		rating.ratee = '<%= rating.user.name %>';
		ratings.push(rating);
		<% end %>
		console.log(ratings);
		generateRatingCircles();
	</script>
</div>